# Generated by Django 3.1.4 on 2020-12-08 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='documentation',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
