# Generated by Django 3.1.4 on 2020-12-09 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0002_tutorial_documentation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorial',
            name='tutorial_file',
        ),
    ]
