# Generated by Django 3.1.4 on 2020-12-09 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0003_remove_tutorial_tutorial_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorial',
            name='url',
        ),
        migrations.AddField(
            model_name='tutorial',
            name='video_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
