# Generated by Django 3.1.4 on 2020-12-09 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0004_auto_20201209_2208'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutorial',
            old_name='documentation',
            new_name='links_to_documentation',
        ),
    ]
